PASO 1 - TMP_CTAS_SERVICIOS:
SELECT 
DISTINCT CTAID.CODCLAVECTA, 
DE_SERV.OPERADORTELCO AS EMPRESA, 
DE_SERV.TIPSERV AS SERVICIO

FROM BCP_UDV_INT.H_CUENTAIDENTIFICACION CTAID
INNER JOIN BCP_RDV_DE_LKDE.DE_CUENTARECAUDADORAOPERADORTELCO DE_SERV
ON TRIM(CTAID.CODCTACOMERCIAL) = TRIM(DE_SERV.CTARECAUDADORA)
WHERE CTAID.FECRUTINA >= 'VARIABLE_FECHA_INICIO_CONSULTA' 
AND CTAID.CODAPP='CTAM';

PASO 1 - TMP_TRANSACCION_SERVICIO:
SELECT 	
TRUD.CODAPPHOST AS CODCANAL,
TRUD.FECTRX AS FECHA_PAGO,
TRUD.FECVCTO AS FECHA_VENCIMIENTO,
SCUM.EMPRESA, 
SCUM.SERVICIO	
FROM BCP_UDV_INT.H_TRANSACCIONRECAUDACION TRUD
INNER JOIN TMP_CTAS_SERVICIOS SCUM 
ON TRUD.CODCLAVECTARECAUDADORA = SCUM.CODCLAVECTA
WHERE (TRUD.FECRUTINA >= 'VARIABLE_FECHA_INICIO_RUTINA_H_TRANSACCIONRECAUDACION' AND TRUD.FECRUTINA <= '{VARIABLE_FECHA_FIN_RUTINA_H_TRANSACCIONRECAUDACION}') 
AND (TRUD.FECTRX >= '{VARIABLE_FECHA_INICIO_CONSULTA}' AND TRUD.FECTRX <= '{VARIABLE_FECHA_FIN_CONSULTA}')
AND ( CASE WHEN SCUM.EMPRESA IN ('CLARO','BITEL', 'ENTEL', 'TELEFONICA')
THEN
CASE WHEN SUBSTR(TRIM(A.NUMSERVEMPRECAUDADORA), 6, 1) = '9'
AND LENGTH(SUBSTR(TRIM(A.NUMSERVEMPRECAUDADORA), 6, 9)) = 9 THEN TRUE
ELSE FALSE END
ELSE TRUE END);

PASO 1 - TMP_CTATARJETACLI:
SELECT 
TC.CODCLAVETARJETA, VP.CODCLAVEPARTYCLI
FROM BCP_UDV_INT.H_TARJETACREDITO TC
INNER JOIN BCP_UDV_INT.H_CUENTATARJETACREDITO VP
ON TC.CODCLAVECTA = VP.CODCLAVECTA
WHERE TC.FECRUTINA= '{varultact}'	AND VP.FECRUTINA='{varultact}';

PASO 1 - TMP_CLIENTE_SERVICIO_EMPRESA
SELECT 
TRL.CODCANAL,
TRL.FECHA_PAGO,
TRL.FECHA_VENCIMIENTO,
TRL.EMPRESA, 
TRL.SERVICIO, 
CASE 
WHEN CTCARGO.CODCLAVEPARTYCLI IS NULL THEN CDEPOS.CODCLAVEPARTYCLI
ELSE CTCARGO.CODCLAVEPARTYCLI END
AS CODCLAVEPARTYCLI

FROM TMP_TRANSACCION_SERVICIO TRL
LEFT JOIN BCP_UDV_INT.H_CUENTAFINANCIERA CTCARGO
ON TRL.CODCLAVECTACARGO = CTCARGO.CODCLAVECTA AND CTCARGO.FECRUTINA='{varultact}' 
AND CTCARGO.CODAPP IN ('CTAM','AHOR')
LEFT JOIN TMP_CTATARJETACLI CDEPOS
ON TRL.CODCLAVETARJETACLI = CDEPOS.CODCLAVETARJETA;


PASO 1 - TMP_CLIENTE_SERVICIO_ORDEN
SELECT 
CODCANAL,
FECHA_PAGO,
FECHA_VENCIMIENTO,
EMPRESA, 
SERVICIO,
CODCLAVEPARTYCLI
ROW_NUMBER() OVER(PARTITION BY CODCLAVEPARTYCLI, EMPRESA, SERVICIO ORDER BY FECHA_PAGO DESC) RNK
FROM TMP_CLIENTE_SERVICIO_EMPRESA 
WHERE RNK = 1;

PASO 1 - TMP_PAGO_SERVICIO_FINAL:
SELECT 
ALERTA.CODCANAL,
ALERTA.FECHA_PAGO,
ALERTA.FECHA_VENCIMIENTO,
ALERTA.EMPRESA, 
ALERTA.SERVICIO,
UNIV.CODINTERNOCOMPUTACIONAL

FROM TMP_CLIENTE_SERVICIO_EMPRESA  AS  ALERTA 
INNER JOIN BCP_DDV_CRMA.TD_UNIVERSOCLIENTECRMA AS UNIV
ON ALERTA.CODCLAVEPARTYCLI== UNIV.CODCLAVEPARTYCLI
WHERE ALERTA.RNK = 1;